on: push
name: build
jobs:
  check-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: cargo, rustc, rust-std
      - run: cargo build
