on:
  push:
    tags:
      - "*.*.*"

name: publish
jobs:
  publish-crate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: cargo
      - run: cargo publish --token ${{ secrets.CRATES_IO_ACCESS_KEY }}
