on:
  push:
    tags:
      - "*.*.*"

name: publish
jobs:
  publish-crate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1.0.3
        with:
          toolchain: 1.77.2
      - run: cargo publish --token ${{ secrets.CRATES_IO_ACCESS_KEY }}
